require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 4

AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - config.ru
    - db/schema.rb
    - db/migrate/*
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Style/Documentation:
  Exclude:
    - app/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - app/**/*

RSpec/ExampleLength:
  Max: 25

Metrics/BlockLength:
  Max: 100

Metrics/LineLength:
  Max: 120
