require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - config.ru
    - db/schema.rb
    - db/migrate/*
    - db/seeds.rb
    - Gemfile
    - Rakefile
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Style/Documentation:
  Exclude:
    - app/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - app/**/*

RSpec/ExampleLength:
  Max: 25

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120

RSpec/ContextWording:
  Exclude:
    - spec/support/shared_contexts/*
